server:
  port: 8761
spring:
  application:
    name: mypro-eureka-server
  security:
    user:
      name: admin
      password: pass1234
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false #是否向服务注册中心注册自己
    fetch-registry: false #是否检索服务
    serviceUrl:
      defaultZone: http://admin:pass1234@${eureka.instance.hostname}:${server.port}/eureka/
    #server:
    #enable-self-preservation: false #设为false，关闭自我保护
    #eviction-interval-timer-in-ms: 5000 # 清理间隔（单位毫秒，默认是60*1000）

  #springboot2.0. 的配置项为：
  #actuator端口
  management:
    server:
      port: 8761
    endpoints:
      web:
        base-path: / #修改访问路径  2.0之前默认是/   2.0默认是 /actuator  可以通过这个属性值修改
        exposure:
          include: '*'  #开放所有页面节点  默认只开启了health、info两个节点
    endpoint:
      health:
        show-details: always #默认是never